// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmnfllxowabaaywzlmdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtbmZsbHhvd2FiYWF5d3psbWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTkzODEsImV4cCI6MjA2MDM3NTM4MX0.IdhwUEc82B-ExaBS-OJOhNUZPKF8M0dTpz00tVuLKYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);